
lifecyle : default
url.primary.tandem : http://cptdnp82.homedepot.com:1200/dev/ibinewcard.ad
url.secondary.tandem : http://cptdnp82.homedepot.com:1200/dev/ibinewcard.ad
timeout.connect.tandem : 20000
timeout.read.tandem : 20000
retry.attempts.tandem : 2
retry.backoffperiod.tandem : 2000


## Development

---

spring.profiles: default

lifecycle: default
url.primary.tandem : http://cptdnp82.homedepot.com:1200/dev/ibinewcard.ad
url.secondary.tandem : http://cptdnp82.homedepot.com:1200/dev/ibinewcard.ad


## Development

---

spring.profiles: development

lifecycle: development
url.primary.tandem : http://cptdnp82.homedepot.com:1200/dev/ibinewcard.ad
url.secondary.tandem : http://cptdnp82.homedepot.com:1200/dev/ibinewcard.ad


## Acceptance
---

spring.profiles: acceptance

lifecycle: acceptance
url.primary.tandem : https://npf-tandem-qa.homedepot.com:80/qa/ibinewcard.qa
url.secondary.tandem : https://npf-tandem-qa.homedepot.com:80/qa/ibinewcard.qa
keystore.pass : "!B!N3wC@r"
keystore.file : CER.PCF.QA.FI.PD.C-3348-IBINewCardTandemClient.jceks


## Production
---

spring.profiles: production

lifecycle: production
url.primary.tandem : https://npf-tandem-atc-pr.homedepot.com:80/pr/ibinewcard.pr
url.secondary.tandem : https://npf-tandem-ssc-pr.homedepot.com:80/pr/ibinewcard.pr
keystore.pass : "N@rjq!2a"
keystore.file : CER.PCF.PR.FI.PD.C-3427-IBINewCardTandemClient.jceks

